---
mongo:
  host: '127.0.0.1'
  port: '27017'
  db: "dxmanager"
environments:
  - label: UI Staging 1
    name: stg1
    host: stg-ui-app01
  - label: UI Staging 2
    name: stg2
    host: stg-ui-app02
  - label: UI Staging 3
    name: stg3
    host: stg-ui-app03
  - label: UI Staging 4
    name: stg4
    host: stg-ui-app04
  - label: UI Cluster 5 and 6
    name: stg-cluster
    host: stage_user_interface_cluster
plugins:
  jenkins:
    params:
      host: "jenkins.bos.dataxu.net"
    deploy:
      matcher: "stg*"
      input:
        name: hash
        placeholder: "Git Commit"
        button_text: "Deploy"
      hook:
        file: jenkins
        method: deploy_ui
      display_values:
        - name: hash
          display_name: Version
        - name: link
          display_name: Deploy Info
